# Generated by Django 2.2.7 on 2019-11-15 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
