# Generated by Django 2.2.7 on 2019-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191115_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
